/**
 * @fileoverview Ionicons 5 by name (the set Rayburst uses, via @vicons/ionicons5).
 * The mock-ups refer to icons by their Ionicons names, as the apps do.
 */
import {
  AddOutline,
  AlbumsOutline,
  AlertCircleOutline,
  ArrowDownOutline,
  ArrowForwardOutline,
  ArrowUpOutline,
  CheckmarkCircleOutline,
  CheckmarkDoneOutline,
  CheckmarkOutline,
  ChevronBackOutline,
  ChevronDownOutline,
  ChevronForwardOutline,
  CloseOutline,
  CloudUploadOutline,
  CodeSlashOutline,
  CopyOutline,
  DesktopOutline,
  DocumentOutline,
  DocumentTextOutline,
  DownloadOutline,
  ExpandOutline,
  FilmOutline,
  FlashOutline,
  FolderOpenOutline,
  GitNetworkOutline,
  Heart,
  HeartOutline,
  InformationCircleOutline,
  LanguageOutline,
  LayersOutline,
  LinkOutline,
  ListOutline,
  LockClosedOutline,
  LogoAndroid,
  LogoApple,
  LogoChrome,
  LogoDocker,
  LogoEdge,
  LogoFirefox,
  LogoGithub,
  LogoTux,
  LogoWindows,
  MagnetOutline,
  MoonOutline,
  OpenOutline,
  OptionsOutline,
  PauseOutline,
  PeopleOutline,
  Play,
  PlayCircleOutline,
  PlayOutline,
  PricetagOutline,
  PulseOutline,
  RadioOutline,
  RefreshOutline,
  RemoveOutline,
  SearchOutline,
  ServerOutline,
  SettingsOutline,
  ShieldCheckmarkOutline,
  SpeedometerOutline,
  SquareOutline,
  StarOutline,
  StopCircleOutline,
  SunnyOutline,
  SwapVerticalOutline,
  TextOutline,
  TrashOutline,
} from '@vicons/ionicons5'
import type { Component } from 'vue'

export const ICONS = {
  'add-outline': AddOutline,
  'albums-outline': AlbumsOutline,
  'alert-circle-outline': AlertCircleOutline,
  'arrow-down-outline': ArrowDownOutline,
  'arrow-forward-outline': ArrowForwardOutline,
  'arrow-up-outline': ArrowUpOutline,
  'checkmark-circle-outline': CheckmarkCircleOutline,
  'checkmark-done-outline': CheckmarkDoneOutline,
  'checkmark-outline': CheckmarkOutline,
  'chevron-back-outline': ChevronBackOutline,
  'chevron-down-outline': ChevronDownOutline,
  'chevron-forward-outline': ChevronForwardOutline,
  'close-outline': CloseOutline,
  'cloud-upload-outline': CloudUploadOutline,
  'code-slash-outline': CodeSlashOutline,
  'copy-outline': CopyOutline,
  'desktop-outline': DesktopOutline,
  'document-outline': DocumentOutline,
  'document-text-outline': DocumentTextOutline,
  'download-outline': DownloadOutline,
  'expand-outline': ExpandOutline,
  'film-outline': FilmOutline,
  'flash-outline': FlashOutline,
  'folder-open-outline': FolderOpenOutline,
  'git-network-outline': GitNetworkOutline,
  heart: Heart,
  'heart-outline': HeartOutline,
  'information-circle-outline': InformationCircleOutline,
  'language-outline': LanguageOutline,
  'layers-outline': LayersOutline,
  'link-outline': LinkOutline,
  'list-outline': ListOutline,
  'lock-closed-outline': LockClosedOutline,
  'logo-android': LogoAndroid,
  'logo-apple': LogoApple,
  'logo-chrome': LogoChrome,
  'logo-docker': LogoDocker,
  'logo-edge': LogoEdge,
  'logo-firefox': LogoFirefox,
  'logo-github': LogoGithub,
  'logo-tux': LogoTux,
  'logo-windows': LogoWindows,
  'magnet-outline': MagnetOutline,
  'moon-outline': MoonOutline,
  'open-outline': OpenOutline,
  'options-outline': OptionsOutline,
  'pause-outline': PauseOutline,
  'people-outline': PeopleOutline,
  play: Play,
  'play-circle-outline': PlayCircleOutline,
  'play-outline': PlayOutline,
  'pricetag-outline': PricetagOutline,
  'pulse-outline': PulseOutline,
  'radio-outline': RadioOutline,
  'refresh-outline': RefreshOutline,
  'remove-outline': RemoveOutline,
  'search-outline': SearchOutline,
  'server-outline': ServerOutline,
  'settings-outline': SettingsOutline,
  'shield-checkmark-outline': ShieldCheckmarkOutline,
  'speedometer-outline': SpeedometerOutline,
  'square-outline': SquareOutline,
  'star-outline': StarOutline,
  'stop-circle-outline': StopCircleOutline,
  'sunny-outline': SunnyOutline,
  'swap-vertical-outline': SwapVerticalOutline,
  'text-outline': TextOutline,
  'trash-outline': TrashOutline,
} satisfies Record<string, Component>

export type IconName = keyof typeof ICONS
